"""Changing the post and author models to fix relationships ind integrate content into Posts

Revision ID: 9c3334b23be2
Revises: 59edc355866a
Create Date: 2023-04-11 12:32:04.799973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3334b23be2'
down_revision = '59edc355866a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.create_foreign_key('post_author_id', 'author', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post_author_id', type_='foreignkey')
        batch_op.drop_column('content')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
